"""Generate the sbm-cli skill's command reference from the Click command tree.

The reference at skills/sbm-cli/references/commands.md is never edited by hand:
it is the `--help` text of every command, rendered at a fixed width so the
output is deterministic. tests/test_skill.py fails when it is stale.

    uv run python scripts/gen_skill_reference.py           # rewrite the file
    uv run python scripts/gen_skill_reference.py --check   # exit 1 if stale
"""
from __future__ import annotations

import sys
import tomllib
from pathlib import Path

import click

from sbm_cli.cli import main

REPO_ROOT = Path(__file__).resolve().parent.parent
REFERENCE_PATH = REPO_ROOT / "skills" / "sbm-cli" / "references" / "commands.md"
HELP_WIDTH = 100


def package_version() -> str:
    with open(REPO_ROOT / "pyproject.toml", "rb") as fh:
        return tomllib.load(fh)["project"]["version"]


def iter_commands(cmd: click.Command, ctx: click.Context):
    """Yield (context, command) depth-first, groups before their subcommands."""
    yield ctx, cmd
    if isinstance(cmd, click.Group):
        for name in sorted(cmd.list_commands(ctx)):
            sub = cmd.get_command(ctx, name)
            if sub is None or sub.hidden:
                continue
            sub_ctx = click.Context(sub, info_name=name, parent=ctx,
                                    terminal_width=HELP_WIDTH,
                                    max_content_width=HELP_WIDTH)
            yield from iter_commands(sub, sub_ctx)


def render() -> str:
    root_ctx = click.Context(main, info_name="sbm",
                             terminal_width=HELP_WIDTH, max_content_width=HELP_WIDTH)
    lines = [
        "# sbm-cli command reference",
        "",
        f"<!-- GENERATED by scripts/gen_skill_reference.py from sbm-cli {package_version()}."
        " Do not edit by hand. -->",
        "",
        f"`--help` output of every command in sbm-cli {package_version()}."
        " If `sbm --version` reports a different",
        "version, trust `sbm <command> --help` on the installed CLI over this file.",
        "",
    ]
    for ctx, cmd in iter_commands(main, root_ctx):
        lines += [f"## `{ctx.command_path}`", "", "```text",
                  cmd.get_help(ctx).rstrip(), "```", ""]
    return "\n".join(lines)


def main_cli(argv: list[str]) -> int:
    content = render()
    current = REFERENCE_PATH.read_text(encoding="utf-8") if REFERENCE_PATH.exists() else ""
    if "--check" in argv:
        if current != content:
            print(f"{REFERENCE_PATH.relative_to(REPO_ROOT)} is stale — "
                  "run: uv run python scripts/gen_skill_reference.py", file=sys.stderr)
            return 1
        return 0
    REFERENCE_PATH.parent.mkdir(parents=True, exist_ok=True)
    REFERENCE_PATH.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {REFERENCE_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main_cli(sys.argv[1:]))
